name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Add SSH key and known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        set -e
        echo "Creating .ssh directory..."
        mkdir -p ~/.ssh
        echo "Creating known_hosts file..."
        touch ~/.ssh/known_hosts

        echo "Adding SSH private key..."
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem

        echo "Adding remote host to known_hosts..."
        ssh-keyscan -H "${REMOTE_HOST}" >> ~/.ssh/known_hosts

        echo "Verifying known_hosts..."
        cat ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        set -e
        echo "Deploying to server..."
        scp -i private_key.pem -r ./* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/products/node-super-app-ci
        echo "Running remote commands..."
        ssh -i private_key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /home/${{ secrets.REMOTE_USER }}/products/node-super-app-ci && npm install --production && pm2 restart all'
        echo "Cleaning up..."
        rm private_key.pem